### ISSUE TITLE
Problem compiling on Windows 7

### ISSUE THREAD

**Issue by ameasure** [percyliang/brown-cluster#3]
I'm trying to compile on Windows 7 using g++ 4.7.2 and GNU Make 3.8.1. When I do I get the following errors: 

C:\Users\ameasure\brown-cluster-master>make
g++ -Wall -g -o wcluster.o -c wcluster.cc
wcluster.cc: In function 'void repcheck()':
wcluster.cc:431:3: error: '__STRING' was not declared in this scope
wcluster.cc:432:3: error: '__STRING' was not declared in this scope
wcluster.cc: In function 'int main(int, char*_)':
wcluster.cc:1072:3: error: '__STRING' was not declared in this scope
make: *_\* [wcluster.o] Error 1

Any idea what's going on?

**Comment by osman-mian** [comment]
I am trying to compile this on Windows7 and getting the same errors
'__STRING' was not declared in this scope
[Note] in expansion of macro 'define_str  '

Please help!

**Comment by chuachilog** [comment]
Maybe you can try to change '__STRING' to use '__STRINGIFY'
